"""Tests for the OpenAPI document generated by the running EPT app."""

import asyncio

from .helpers import create_api_shell_test_app, get_many
from tests.conftest import contract


@contract
def test_service_routes_have_explicit_response_models() -> None:
    """The OpenAPI document should not have any implicit response models."""
    app = create_api_shell_test_app()
    openapi = asyncio.run(get_many("/openapi.json", app=app))[0].json()
    paths = openapi["paths"]

    assert openapi["openapi"] == "3.1.0"
    assert paths["/v1"]["get"]["responses"]["200"]["content"]["application/json"]["schema"] == {
        "$ref": "#/components/schemas/ApiIndex"
    }
    assert "/" not in paths
    assert "/health" not in paths
    assert "/healthz" not in paths






@contract
def test_openapi_marks_protected_routes_as_bearer_protected() -> None:
    """OpenAPI should tell clients which routes need bearer authentication."""
    app = create_api_shell_test_app()
    paths = asyncio.run(get_many("/openapi.json", app=app))[0].json()["paths"]
    public_paths = {"/v1", "/v1/auth"}

    for path, operations in paths.items():
        for operation in operations.values():
            if path in public_paths:
                assert "security" not in operation
            else:
                assert operation["security"] == [{"HTTPBearer": []}]


@contract
def test_openapi_uses_professional_v1_conventions() -> None:
    """OpenAPI should expose a stable, versioned, client-ready contract."""
    app = create_api_shell_test_app()
    schema = asyncio.run(get_many("/openapi.json", app=app))[0].json()
    paths = schema["paths"]

    assert set(paths) == {
        "/v1",
        "/v1/auth",
        "/v1/protected",
    }
    bearer_scheme = schema["components"]["securitySchemes"]["HTTPBearer"]
    assert bearer_scheme["type"] == "http"
    assert bearer_scheme["scheme"] == "bearer"
    assert bearer_scheme["bearerFormat"] == "JWT"
    assert paths["/v1"]["get"]["operationId"] == "getApiIndexV1"
    auth_operation = paths["/v1/auth"]["post"]
    assert auth_operation["operationId"] == "createEditoTokensV1"
    auth_json = auth_operation["requestBody"]["content"]["application/json"]
    assert auth_json["example"] == {
        "grant_type": "password",
        "username": "YOUR_EDITO_USERNAME",
        "password": "YOUR_EDITO_PASSWORD",
    }
    assert auth_json["schema"]["oneOf"] == [
        {"$ref": "#/components/schemas/EditoPasswordTokenRequest"},
        {"$ref": "#/components/schemas/EditoRefreshTokenRequest"},
    ]
    assert auth_json["schema"]["discriminator"] == {
        "propertyName": "grant_type",
        "mapping": {
            "password": "#/components/schemas/EditoPasswordTokenRequest",
            "refresh_token": "#/components/schemas/EditoRefreshTokenRequest",
        },
    }
    assert schema["components"]["schemas"]["EditoPasswordTokenRequest"]["required"] == [
        "grant_type",
        "username",
        "password",
    ]
    assert schema["components"]["schemas"]["EditoRefreshTokenRequest"]["required"] == [
        "grant_type",
        "refresh_token",
    ]
    assert paths["/v1/protected"]["post"]["operationId"] == "exerciseProtectedApiBehaviorV1"


@contract
def test_openapi_documents_problem_details_responses():
    """Protected API operations should document Problem Details failure bodies."""
    app = create_api_shell_test_app()
    paths = asyncio.run(get_many("/openapi.json", app=app))[0].json()["paths"]

    operation = paths["/v1/protected"]["post"]
    assert "application/problem+json" in operation["responses"]["401"]["content"]
    assert "application/problem+json" in operation["responses"]["422"]["content"]
    assert "application/problem+json" in operation["responses"]["502"]["content"]
    for response in operation["responses"].values():
        content = response.get("content", {})
        if "application/problem+json" in content:
            assert set(content) == {"application/problem+json"}
